root: true
env:
  browser: true
  commonjs: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  tsconfigRootDir: '.'
  project: './tsconfig.json'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  # - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
plugins:
  - '@typescript-eslint'
rules:
  "@typescript-eslint/no-explicit-any": "off"
